[theme]
primaryColor = "#1f77b4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
# Necessário para rodar dentro do container/EasyPanel atrás do proxy reverso (Traefik)
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[ui]
hideTopBar = false
hideSidebarNav = false
